### ISSUE TITLE
Missing 'results/target_queries/hotpotqa.json'

### ISSUE THREAD

**Issue by tamtakapanadze** [sleeepeer/PoisonedRAG#10]
" FileNotFoundError: [Errno 2] No such file or directory: 'results/target_queries/hotpotqa.json' "
Is prepare_datasets.py responsible for creating this directory, or should I download the datasets under results/target_queries/ myself?
I only have 'adv_targeted_results' and 'beir_results' folders under results.

**Comment by tamtakapanadze** [comment]
Found [https://github.com/sleeepeer/PoisonedRAG/issues/8](url)

**Comment by sleeepeer** [comment]
Thanks for pointing it out, will remove `results/target_queries/` related code.

**Comment by sleeepeer** [comment]
Hi, I've fixed the path bug in the latest commit and you could have a try. Feel free to reopen this issue if have further questions! Thanks again!
