### ISSUE TITLE
4.2.1 A straightforward solution is to use gradient descent-based methods [53, 78] to optimize R.  WHY R???

### ISSUE THREAD

**Issue by try2love** [sleeepeer/PoisonedRAG#13]
In subsection 4.2.1 of the article, you mentioned the use of gradient descent to optimize the attacker's target answer R, why is it optimized for R? Isn't it true that the attacker has identified a desired target answer to the current target question, and then uses gradient descent to optimize the text I that satisfies the generation criteria? I'm confused here and look forward to your answers.

在文章的4.2.1小节中，你提到使用梯度下降的方法来优化攻击者的目标回答R，为什么是针对R来优化？难道不是攻击者针对当前的目标问题已经明确了一个期望的目标回答，然后使用梯度下降的方式来优化满足生成条件的文本I吗？这里我很困惑，期待你的解答。

**Comment by sleeepeer** [comment]
Hi! Thanks for your interest in our paper and thanks for pointing it out!
We checked our current version and found that this is a typo, which should be "optimize $I$ such that an LLM will output $R$". We will fix this typo in our next version.
Thanks again for pointing this out and thanks for your attention!
