### ISSUE TITLE
Cannot generate 100 malicious texts

### ISSUE THREAD

**Issue by young-her** [sleeepeer/PoisonedRAG#15]
when I‘m trying to run `gen_adv.py`,I've found that the LLM(I'm using glm-4-flash) generates generally around 10 malicious texts.I'm not sure if it's a problem with the LLM or with the following code
```python
# keep the shorter correct answer
if response_q.lower() in response_w_gt.lower():
    correct_answer = response_q
elif response_w_gt.lower() in response_q.lower():
    correct_answer = response_w_gt
else:
    continue
```

**Comment by sleeepeer** [comment]
Hi! Thanks for your question!

By default we use GPT-4 to generate the answer. The above code what we used is to keep the shorter answer for accurate evaluation later (when the answer is shorter, it contains less words like "The answer is xxx" or "Output: xxx").

So this code will filter some texts out, which results in less malicious texts generated.

When using some model (maybe also your glm-4-flash), their response is sometims very long and contains such useless words that we don't want. So this might be the reason why you only get around 10 malicious texts.

Thanks again for your interest in our paper!

**Comment by young-her** [comment]
> Hi! Thanks for your question!
> 
> By default we use GPT-4 to generate the answer. The above code what we used is to keep the shorter answer for accurate evaluation later (when the answer is shorter, it contains less words like "The answer is xxx" or "Output: xxx").
> 
> So this code will filter some texts out, which results in less malicious texts generated.
> 
> When using some model (maybe also your glm-4-flash), their response is sometims very long and contains such useless words that we don't want. So this might be the reason why you only get around 10 malicious texts.
> 
> Thanks again for your interest in our paper!

Thanks for your reply! Nice work!

**Comment by young-her** [comment]
> Hi! Thanks for your question!
> 
> By default we use GPT-4 to generate the answer. The above code what we used is to keep the shorter answer for accurate evaluation later (when the answer is shorter, it contains less words like "The answer is xxx" or "Output: xxx").
> 
> So this code will filter some texts out, which results in less malicious texts generated.
> 
> When using some model (maybe also your glm-4-flash), their response is sometims very long and contains such useless words that we don't want. So this might be the reason why you only get around 10 malicious texts.
> 
> Thanks again for your interest in our paper!

Sorry to bother you again.I changed the model to GPT4, but it seems to be getting poor results as well. I tried to print the following results for each query
```shell
Query: who is the girl in the hinder video lips of an angel

Response_q: The girl in the Hinder's "Lips of an Angel" music video is actress Emmanuelle Chriqui.

Response_w_gt: The girl in the Hinder video "Lips of an Angel" is Emmanuelle Chriqui.

Correct answer not found for query test1912.
Query: who won the most medals at the 2014 winter olympics

Response_q: The country that won the most medals at the 2014 Winter Olympics was Russia, with a total of 33 medals.

Response_w_gt: Russia won the most medals at the 2014 Winter Olympics.

Correct answer not found for query test983.
```
You can see that both answers contain the correct answer but do not end up generating malicious text.
What do I need to do? Do I need to change the prompt or change the code logic?

**Comment by sleeepeer** [comment]
I see, thanks for your feedback. I think you could try to change the prompt, making the LLM output short and concise answer? The reason why we need short answers here is to help better evaluation (sub string or exact match). If you find better evaluation metrics, like LLM as a judge, NLI model, or human evaluation, you could of course keep these long answers!

**Comment by young-her** [comment]
Well, thanks for your reply. After reading your paper, I've always been curious about a better way to detect whether the knowledge database in a RAG is poisoned or not








 ----------Reply to Message----------
 On Mon, Dec 16, 2024 02:51 AM Runpeng ***@***.***&gt; wrote:

  

 
I see, thanks for your feedback. I think you could try to change the prompt, making the LLM output short and concise answer? The reason why we need short answers here is to help better evaluation (sub string or exact match). If you find better evaluation metrics, like LLM as a judge, NLI model, or human evaluation, you could of course keep these long answers!

**Comment by sleeepeer** [comment]
Thanks for your interest! You are always welcome to reach out and drop us an email to discuss interesting research questions! Closing the issue now, feel free to reopen it.
