### ISSUE TITLE
Question about replicating the code

### ISSUE THREAD

**Issue by Zongdanyang** [sleeepeer/PoisonedRAG#2]
Hello, I am very interested in your paper, so I have recently been replicating the code you provided. When I tried to reproduce the results with top_k=50, I encountered a RuntimeError: The size of tensor a (4096) must match the size of tensor b (7933) at non-singleton dimension 3 error. I would like to ask if there is a fixed dimension related to k somewhere, and where should I modify it? Thank you.

**Comment by sleeepeer** [comment]
Hi, thanks for pointing it out. Could you please specify your experimental setting, (e.g. what LLM you used? Your issue about dimension seems to come from a local model (llama2 or vicuna)).

**Comment by Zongdanyang** [comment]
I used the llama-7b-chat-hf model. Below are my experimental settings:
test_params = {
    # beir_info
    'eval_model_code': "contriever",
    'eval_dataset': "nq",
    'split': "test",
    'query_results_dir': 'main',

    # LLM setting 
    'model_name': 'llama7b', 
    'use_truth': False,
    'top_k': 50,
    'gpu_id': 1,

    # attack
    'attack_method': 'LM_targeted',
    'adv_per_query': 5,
    'score_function': 'dot',
    'repeat_times': 10,
    'M': 10,
    'seed': 12,

    'note': None
}

**Comment by sleeepeer** [comment]
I replicated your setting and found that **llama-7b-chat-hf has a max_length of 4096**. When top_k=50, the context could be very long (with a length of 7933). Our top_k=50 results in the Appendix (Figure21-26) were tested on **PaLM-2 (our default model)**, which is an online API and supports longer context input. So I suggest you test top_k=50 using PaLM-2.

Here is a screenshot from [llama-2-7b's HuggingFace page](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf), which indicates that llama-2 only supports a 4k context length (i.e. 4096).
<img width="563" alt="image" src="https://github.com/sleeepeer/PoisonedRAG/assets/79324989/da78febf-20d0-4ff1-93f7-6dfd24518a4f">

**Comment by Zongdanyang** [comment]
Thank you for your suggestion!

**Comment by sleeepeer** [comment]
Welcome! If you have further questions, feel free to contact me!
