### ISSUE TITLE
Questions about this paper

### ISSUE THREAD

**Issue by Zongdanyang** [sleeepeer/PoisonedRAG#3]
Hi,First,thank you for  helping me reproduce the results of this paper last time.Now I would like to ask how you found the correct answers for each question in your repo's three datasets and what method you used to set the target answers. Thank you.

**Comment by sleeepeer** [comment]
Hi! The three datasets came from [BEIR](https://github.com/beir-cellar/beir) benchmark. For each dataset, there is a 'qrels' part that contains ground truth contexts for each question in the dataset. We use those ground truth contexts to query GPT-4 to get the correct answers. For target answers (i.e. incorrect answers), you could refer to **Section 5.1 'Target questions and answers'** in our paper.

**Comment by Zongdanyang** [comment]
Ok，thanks
