### ISSUE TITLE
Can you provide a Python file for generating target_answer and adv_text?

### ISSUE THREAD

**Issue by Zongdanyang** [sleeepeer/PoisonedRAG#4]
Hello, I noticed that there are many parts in the dataset you provided that have not been experimented on yet. Therefore, I would like to conduct experiments on this part. Would you be able to provide me with the relevant Python files for generating target_answer and adv_text? Thank you!

**Comment by sleeepeer** [comment]
Hi! We will release the code when we finish organizing it. Or you could contact me via email and I can provide you with the code.
