### ISSUE TITLE
Scripts generate files in PoisonedRAG/results /beir_results/

### ISSUE THREAD

**Issue by Allencheng97** [sleeepeer/PoisonedRAG#5]
Dear author,

   Thank you for your great work. I have some question regarding the precompute json file in the repo. 

1.  Is the file in beir_results folder key represents the target question and corresponding article dot similarity? 
2.  Would you be able to provide the scripts to generate this file in the repo? I will really appreciate  it since current file i have no idea the test_num match which question. 

Thank you very much for your time. I am looking forward to hearing from you soon.

**Comment by sleeepeer** [comment]
Thank you very much for pointing it out.
1.Yes, beir_results contain top-100 dot similarity for each target question.
2.I've sent the file to you via email and we will update our repo, thank you!
