### ISSUE TITLE
How to build beir_results?

### ISSUE THREAD

**Issue by ShiJiawenwen** [sleeepeer/PoisonedRAG#6]
Hello, thanks for your interesting work! I have some code questions after I run your code. If I want to transfer to other dataset, is the first thing to generate beir results, right? But I can not find the code? Can you help me to solve this? Many thanks.

**Comment by sleeepeer** [comment]
Thanks! Will upload the code soon in the next week.

**Comment by sleeepeer** [comment]
Hi! Thanks for pointing it out! I've uploaded **evaluate_beir.py** in the latest commit, which is what we used to generate beir_results for beir datasets. If you want to use your own datasets, please modify this file to load your dataset and prepare it as the beir format **(corpus, queries, qrels)**, and use **evaluate_beir.py** to generate results for it.

**Comment by ShiJiawenwen** [comment]
Many thanks!

**Comment by sleeepeer** [comment]
You are welcome! Feel free to reopen this issue or email me if you have further questions!
