### ISSUE TITLE
OpenAI API key

### ISSUE THREAD

**Issue by c0ding4ever** [sleeepeer/PoisonedRAG#9]
Hello, thank you again for uploading your scripts!

I am trying to generate target results with my own data but my OpenAI account has exceeded its quota.

I was wondering approximately how many credits were needed to generate the results for 1 dataset? Trying to estimate how many credits to buy.

**Comment by sleeepeer** [comment]
You could use cheaper models (such as GPT-4o-mini) to save credits. The prices of GPT-4o and GPT-4 are a little bit high. We used GPT-4 at that time, but the price has changed, so you could refer to their new pricing to estimate the cost.
